version: '3'

services:
  web:
    build: .
    image: graphsp-web:latest
    command: >
      sh -c "python manage.py migrate --settings=graphspace.settings.local && python manage.py runserver 0.0.0.0:8000 --settings=graphspace.settings.local"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:9.6.2
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: graphspace_user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: graphspace_db
    networks:
      - webnet
    ports:
      - "5432:5432"

networks:
  webnet:

volumes:
  db_data:
